Repository veeso/termscp, pull requests merged in 2021-09, with the labels that each got.

#63 Aws s3
  .github/actions-rs/grcov.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/man.md
  src/config/bookmarks.rs
  src/config/serialization.rs
  src/filetransfer/mod.rs
  src/filetransfer/params.rs
  src/filetransfer/transfer/ftp.rs
  src/filetransfer/transfer/mod.rs
  src/filetransfer/transfer/s3/mod.rs
  src/filetransfer/transfer/s3/object.rs
  src/filetransfer/transfer/scp.rs
  src/filetransfer/transfer/sftp.rs
  src/host/mod.rs
  src/lib.rs
  src/main.rs
  src/system/bookmarks_client.rs
  src/ui/activities/auth/bookmarks.rs
  src/ui/activities/auth/misc.rs
  src/ui/activities/auth/mod.rs
  src/ui/activities/auth/update.rs
  src/ui/activities/auth/view.rs
  src/ui/activities/filetransfer/actions/copy.rs
  src/ui/activities/filetransfer/actions/newfile.rs
  src/ui/activities/filetransfer/actions/rename.rs
  src/ui/activities/filetransfer/lib/transfer.rs
  src/ui/activities/filetransfer/misc.rs
  src/ui/activities/filetransfer/mod.rs
  src/ui/activities/filetransfer/session.rs
  src/ui/activities/filetransfer/update.rs
  src/ui/activities/setup/view/setup.rs
  src/utils/parser.rs
  src/utils/path.rs
  src/utils/test_helpers.rs
Labels: new feature

#64 Self update
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  dist/build/docker.sh
  dist/build/freebsd.sh
  dist/build/macos.sh
  dist/build/windows.ps1
  dist/build/x86_64/Dockerfile
  docs/man.md
  src/lib.rs
  src/main.rs
  src/support.rs
  src/system/auto_update.rs
  src/system/mod.rs
  src/ui/activities/auth/misc.rs
  src/ui/activities/auth/mod.rs
  src/ui/activities/auth/update.rs
  src/ui/activities/auth/view.rs
  src/utils/git.rs
  src/utils/mod.rs
Labels: new feature

#65 Prompt user when about to replace an existing file
  CHANGELOG.md
  docs/man.md
  src/config/params.rs
  src/config/serialization.rs
  src/system/config_client.rs
  src/ui/activities/filetransfer/actions/find.rs
  src/ui/activities/filetransfer/actions/mod.rs
  src/ui/activities/filetransfer/actions/save.rs
  src/ui/activities/filetransfer/lib/transfer.rs
  src/ui/activities/filetransfer/mod.rs
  src/ui/activities/filetransfer/session.rs
  src/ui/activities/filetransfer/update.rs
  src/ui/activities/filetransfer/view.rs
  src/ui/activities/setup/mod.rs
  src/ui/activities/setup/update.rs
  src/ui/activities/setup/view/setup.rs
  src/ui/store.rs
Labels: new feature

#67 Translate doc into simplified Chinese
  docs/man-zh.md
Labels: documentation

#68 Notifications
  .github/actions-rs/grcov.yml
  .github/workflows/coverage.yml
  .github/workflows/freebsd.yml
  .github/workflows/linux.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/man-en.md
  docs/man-zh.md
  install.sh
  src/config/params.rs
  src/config/serialization.rs
  src/lib.rs
  src/support.rs
  src/system/config_client.rs
  src/system/mod.rs
  src/system/notifications.rs
  src/ui/activities/auth/misc.rs
  src/ui/activities/auth/mod.rs
  src/ui/activities/filetransfer/lib/transfer.rs
  src/ui/activities/filetransfer/misc.rs
  src/ui/activities/filetransfer/mod.rs
  src/ui/activities/filetransfer/session.rs
  src/ui/activities/setup/mod.rs
  src/ui/activities/setup/update.rs
  src/ui/activities/setup/view/setup.rs
  src/ui/components/bytes.rs
  src/ui/components/mod.rs
  src/utils/fmt.rs
  src/utils/parser.rs
Labels: documentation, new feature
